.\" Manpage for client_cfg_purge.
.\" Contact pierluigi.greto@bisdn.de to correct errors or typos.
.TH man 8 "23 January 2019" "1.0" "client_cfg_purge man page"
.SH NAME
client_cfg_purge \- will purge all the switch configurations. This operation cannot be undone
.SH SYNOPSIS
.B client_cfg_purge
.SH DESCRIPTION
.PP
Purge all the switch configurations. This operation cannot be undone.
.TP
\fB\-h\fR, \fB\--help\fR
display help and exit
.TP
\fB\--usage\fR
give a short usage message
.SH SEE ALSO
client_classcolortable_dump(1), client_debugcomp(1), client_debuglvl(1), client_drivshell(1), client_event(1), client_flowtable_dump(1), client_grouptable_dump(1), client_mirror_port_dump(1), client_oam_dump(1), client_port_table_dump(1), client_tunnel_dump(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Man page originally written by Pierluigi Greto <pierluigi.greto@bisdn.de>.
